# Intersight credentials are only required if downloading techsupport from intersight
# Intersight OAuth client ID
client_id: <key>
# Intersight Oauth client secret
client_secret: <secret>

hosts:
  - source: ucsm
    host: <host>
    username: <usr>
    password: <pwd>

  - source: intersight
    vip: <x.x.x.x>

  # additional TS download targets...
