# Intersight credentials are only required if downloading techsupport from intersight
# Intersight API key
api_key: <key>
# Intersight secret key file
secret_key_file: <filename>

hosts:
  - source: ucsm
    host: <host>
    username: <usr>
    password: <pwd>

  - source: intersight
    vip: <x.x.x.x>

  # additional TS download targets...
